### ISSUE TITLE
Allow user to define amino acid list when parsing data

### ISSUE THREAD

**Issue by meganwojciechowicz** [allydunham/deepscanscape#1]
Is there currently a way to allow the user to add stop (*) and synonymous (=) variants to the amino_acid list and update aa_3_to_1 when using the parse_deep_scan function?

**Comment by allydunham** [comment]
That isn't currently supported unfortunately.

Supporting synonymous variants is reasonably easy though. Currently you should just pre-process your data frame by setting any instances of = to the corresponding wt before calling parse_deep_scan. It would be easy to add this functionality to the package too - I will do it if I have time for a patch or I'd be happy to accept a pull request.

Supporting stop codons is more difficult, depending on what you want to do with them? It would be reasonably easy to allow them to be imported correctly but the rest of the package wouldn't meaningfully support them. I might be able to make a patch that adds some basic support, but it would take a bit more time.

Incidentally if you want to use the rest of the package you should use deep_mutational_scan, which returns the correct object type, as opposed to parse_deep_scan. If you just want to process some DMS data into regular R data frames then it would probably be easiest to directly copy the bits of code you need, for example from `parse.R` and edit what you need to stop * being filtered and support =.

**Comment by meganwojciechowicz** [comment]
Currently I'm utilizing the package for parsing only and need to keep the * and = for downstream analyses. I can copy the bits I need to make it fit like you suggest. Thank you for your reply!

**Comment by allydunham** [comment]
Great, I think using a slightly modified version should work best for you then. It is still a gap in the package though, so I'll try to add some support for */= when I have a bit of time.

**Comment by allydunham** [comment]
I have now added basic support for importing synonymous variants marked with "=" and optional early stop mutants. They are added as a new column in the `deep_mutational_scan` object and are mainly for downstream user use - the package doesn't impute them (I have some ideas but there doesn't seem a good general way to do this) and they are only used for the basic ER heatmap.
